# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6fe6edd8109948ff8919805afc807f604cca31b5abb9e7507542046611563a72603ee03db8dacf51e2c4fe6796ed98cf2b2c2666c0bdc8210cd4e6af435be8f

test:
  secret_key_base: 4117879d69c980ef2e71b6649302c5e9c17c6786509aba2854604f6ec44653bc5d0f35eede3fc4d932d956371b4cc57781200e1dc2565ab9d2e380b0ad35760c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
